script_settings:
  interval: 5   # Time between shots in seconds
  frames: 100   # Total number of frames to capture

camera_settings:
  iso: '800'
  whitebalance: 'Auto'
  shutterspeed: '1/125'
  aperture: '4.5'
#   shutterspeed: '1/125'
#   aperture: '4.5'
  focusmode: 'Manual'
  # focusmode: 'AI Focus'

tripod_settings:
  pan_start: 0
  pan_end: 30
  tilt_start: 0
  tilt_end: 30
  microstep_resolution: '1/8' # full, 1/2, 1/4, 1/8, 1/16
  movement_mode: 'incremental' # 'incremental' or 'continuous'
  settle_time: 0.5 # seconds to wait for vibrations to settle
  command_timeout: 5.0 # seconds to wait for a command to complete
